# -*- coding: utf-8 -*-
"""Lab 6 (final project)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kckbBYVoakDxYFRc6Isyr7gZAQ4rDXKX

# Section One

**(a)**
"""

# Commented out IPython magic to ensure Python compatibility.
#Importing some libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
from matplotlib.cm import rainbow
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')

#Libraries for tree and classifying the data
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
#Library for splitting the data for test and training
from sklearn.model_selection import train_test_split

#Uploading our dataset from the laptop
from google.colab import files
uploaded= files.upload()
#Assigning it to a "dataset" variable
dataset= pd.read_csv('Heart Disease Prediction.csv')

"""**(b)**"""

#Drawing histograms for analysis
dataset.hist(figsize=(15,15))

"""# Section Two

**(a)**
"""

#Splitting the data for test and training
y = dataset['Heart Disease']
X = dataset.drop(['Heart Disease'], axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

"""**(b)**"""

#Training the data for preparation
dt_scores = []
for i in range(1, len(X.columns) + 1):
    dt_classifier = DecisionTreeClassifier(max_features = i, random_state = 0)
    dt_classifier.fit(X_train, y_train)
    dt_scores.append(dt_classifier.score(X_test, y_test))

"""**(c)**"""

plt.plot([i for i in range(1, len(X.columns) + 1)], dt_scores, color = 'blue')
for i in range(1, len(X.columns) + 1):
    plt.text(i, dt_scores[i-1], (i, dt_scores[i-1]))
plt.xticks([i for i in range(1, len(X.columns) + 1)])
plt.xlabel('Features')
plt.ylabel('Scores')
plt.title('Decision Tree Classifier scores for diff. no. of features')

"""**(d)**"""

#Setting the features name for the tree model
features= ["Age", "Sex", "Chest Pain type", "BP", "FBS over 120", "EKG results", "Max HR", "Exercise angina", "ST depression", "Slope of ST", "Number of vessels fluro", "Thallium", "Heart Disease"]

#Plotting tree of our train set
clasifier = tree.DecisionTreeClassifier()
clasifier = clasifier.fit(X_train, y_train)
plt.figure(figsize=(50,20))  # set plot size (denoted in inches)
tree.plot_tree(clasifier, fontsize=10, feature_names=features)
plt.show()

"""**(e)**"""

clf_model = DecisionTreeClassifier(criterion="gini", random_state=0, min_samples_leaf=5)
clf_model.fit(X_train,y_train)
y_predict = clf_model.predict(X_test)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(y_test,y_predict)